'use strict';
// Catalog -> standalone Lua 5.1 module. No runtime translation requests.
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),catalog=require('./locales.json');
const convert=require('opencc-js').Converter({from:'cn',to:'tw'});
const traditional={};
for(const key of Object.keys(catalog.zh))traditional[key]=convert(key);
for(const [key,value]of Object.entries(catalog.en))traditional[key]=convert(value);
Object.assign(traditional,require('./locales-zhTW.json'));
// Conversion must never alter format placeholders or WoW color markup.
for(const [key,value]of Object.entries(traditional)){
 for(const pattern of [/%[-+\d.]*[sdf]/g,/\|c[0-9a-f]{8}|\|r/g]){
  if(JSON.stringify(key.match(pattern)||[])!==JSON.stringify(value.match(pattern)||[]))throw Error('Unsafe zhTW format: '+key);
 }
}
// Convert bundled reference text at build time, never player messages or API results.
const reference={};
function collect(node){
 if(!node||typeof node!=='object')return;
 if(node.type==='StringLiteral'){
  const text=Buffer.from(node.value,'latin1').toString('utf8');
  if(/[\u3400-\u9fff]/.test(text)){const result=convert(text);if(result!==text)reference[text]=result;}
 }
 for(const value of Object.values(node)){if(Array.isArray(value))value.forEach(collect);else if(value&&typeof value==='object')collect(value);}
}
for(const file of ['DungeonData.lua','Adventure.lua'])collect(require('luaparse').parse(fs.readFileSync(path.join(root,'addon/WoWAI',file)).toString('latin1'),{encodingMode:'pseudo-latin1'}));
const quote=s=>'"'+s.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r/g,'\\r').replace(/\n/g,'\\n').replace(/\t/g,'\\t')+'"';
const table=o=>'{\n'+Object.entries(o).map(([k,v])=>'    ['+quote(k)+']='+quote(v)).join(',\n')+'\n}';
fs.writeFileSync(path.join(root,'addon/WoWAI/Locale.lua'),`-- Generated by tools/build-locales.js. UI strings only; never translate user text.
local Locale = {}
WoWAILocale = Locale
local EN = ${table(catalog.zh)}
local ZH = ${table(catalog.en)}
local TW = ${table(traditional)}
local REFERENCE_TW = ${table(reference)}
function Locale.Get()
    local setting = WoWAIDB and WoWAIDB.settings and WoWAIDB.settings.language
    if setting == 'zhCN' or setting == 'zhTW' or setting == 'enUS' then return setting end
    local client = GetLocale and GetLocale() or 'enUS'
    return (client == 'zhCN' or client == 'zhTW') and client or 'enUS'
end
function Locale.Text(key)
    if key == nil then return '' end
    if Locale.Get() == 'enUS' then return EN[key] or key end
    if Locale.Get() == 'zhTW' then return TW[key] or key end
    return ZH[key] or key
end
function Locale.Traditional(value) return REFERENCE_TW[value] or TW[value] or value end
function Locale.Reference(value)
    if Locale.Get() == 'zhTW' then return Locale.Traditional(value) end
    return value
end
-- Client names must still match when the UI language is manually overridden.
function Locale.SameName(reference, actual)
    return reference == actual or Locale.Traditional(reference) == actual
end
-- Keep reference matching fields immutable. Live game names take precedence at callers.
function Locale.Field(record, field)
    if not record then return '' end
    field = field or 'name'
    if Locale.Get() == 'enUS' then
        local translated = record[field .. 'En']
        if translated and translated ~= '' then return translated end
        if field == 'name' and record.en and record.en ~= '' then return record.en end
    end
    return Locale.Reference(record[field] or '')
end
function Locale.ApplyPopups()
    for key, popup in pairs(StaticPopupDialogs or {}) do
        if key:match('^WOWAI') then
            for _, field in ipairs({'text','button1','button2','button3','button4'}) do
                if type(popup[field]) == 'string' then popup[field] = Locale.Text(popup[field]) end
            end
        end
    end
end
function Locale.Set(value)
    value = tostring(value or ''):lower()
    local modes = {auto='auto',zhcn='zhCN',zhtw='zhTW',zh='zhCN',enus='enUS',engb='enUS',en='enUS'}
    local selected = modes[value]
    if not selected or not WoWAIDB or not WoWAIDB.settings then return false end
    WoWAIDB.settings.language = selected
    print('|cff66ccff[WoW AI]|r '..Locale.Text('语言已保存；输入 /reload 后生效。'))
    return true
end
`);
console.log('Locale.lua: '+(Object.keys(catalog.zh).length+Object.keys(catalog.en).length)+' translated strings');
